### ISSUE TITLE
Roadmap.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/terminal-twitch-chat#1]
Highest priority at the top, lowest at the bottom.

- [x] GitHub Workflows.
- [x] Precommit.
- [x] Dependabot.
- [ ] Scrolling:
    - [x] Auto
    - [ ] Manual
        - [ ] Bold text on selection
        - [ ] Actions on select (copy text, delete message, etc)
- [x] https://github.com/Xithrius/terminal-twitch-chat/pull/7
- [x] https://github.com/Xithrius/terminal-twitch-chat/pull/10
- [x] https://github.com/Xithrius/terminal-twitch-chat/pull/14
- [ ] Seeing who's in chat in a different window.
- [ ] Document everything.
- [ ] Command suggestions (if possible).
- [x] https://github.com/Xithrius/terminal-twitch-chat/pull/17
- [ ] Cycle through different chats by `ctrl + tab` and `ctrl + shift + tab` for right/left movement.
- [ ] Unit test as much as necessary.

**Comment by simonsan** [comment]
Something for mods would be nice, like to easily timeout and ban people with selection of a message and giving a timeframe for the timeout.

**Comment by Xithrius** [comment]
@simonsan Regular commands already work when sending them through the TUI, such as `/clear`. 

*Maybe* a section for suggestions for commands and their input might be possible, but Twitch's IRC documentation is already very minimal in it's ways of communicating features.

If I or anyone find a way for moderator actions, it'll most likely be implemented unless the levels of scuffed are too high.

**Comment by simonsan** [comment]
@Xithrius Here is an overview over the commands:
https://help.twitch.tv/s/article/chat-commands?language=en_US

**Comment by Xithrius** [comment]
@simonsan Thank you for that article. What I'm worried about here is with updates to Twitch over time, I'd have to continuously look at this document. If I do end up making these commands with help/suggestions, I'll be automating it.

**Comment by simonsan** [comment]
> @simonsan Thank you for that article. What I'm worried about here is with updates to Twitch over time, I'd have to continuously look at this document. If I do end up making these commands with help/suggestions, I'll be automating it.

I understand that. Twitch API in general is not well-documented and can change pretty fast without announcement. I do feel that the IRC commands are pretty stable though. I'm a moderator in some Twitch channels and the basics haven't changed since a couple years.

**Comment by Xithrius** [comment]
I've updated the roadmap to seek possibilities and/or implementations of command suggestions.

**Comment by Xithrius** [comment]
Closing this issue in favor of the [Roadmap Project](https://github.com/Xithrius/terminal-twitch-chat/projects/1).
